'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
exports.Sigmoid = exports.FuzzyFunction = exports.Constant = exports.Trapezoid = exports.Triangle = exports.ReverseGrade = exports.Grade = exports.Shape = exports.Logic = void 0;
var logic_1 = require("./logic");
Object.defineProperty(exports, "Logic", { enumerable: true, get: function () { return logic_1.Logic; } });
var shape_1 = require("./curve/shape");
Object.defineProperty(exports, "Shape", { enumerable: true, get: function () { return shape_1.Shape; } });
var grade_1 = require("./curve/grade");
Object.defineProperty(exports, "Grade", { enumerable: true, get: function () { return grade_1.Grade; } });
var reverse_grade_1 = require("./curve/reverse-grade");
Object.defineProperty(exports, "ReverseGrade", { enumerable: true, get: function () { return reverse_grade_1.ReverseGrade; } });
var triangle_1 = require("./curve/triangle");
Object.defineProperty(exports, "Triangle", { enumerable: true, get: function () { return triangle_1.Triangle; } });
var trapezoid_1 = require("./curve/trapezoid");
Object.defineProperty(exports, "Trapezoid", { enumerable: true, get: function () { return trapezoid_1.Trapezoid; } });
var constant_1 = require("./curve/constant");
Object.defineProperty(exports, "Constant", { enumerable: true, get: function () { return constant_1.Constant; } });
var fuzzy_function_1 = require("./curve/fuzzy-function");
Object.defineProperty(exports, "FuzzyFunction", { enumerable: true, get: function () { return fuzzy_function_1.FuzzyFunction; } });
var sigmoid_1 = require("./curve/sigmoid");
Object.defineProperty(exports, "Sigmoid", { enumerable: true, get: function () { return sigmoid_1.Sigmoid; } });
//# sourceMappingURL=index.js.map